### ISSUE TITLE
apache50 start NON_EXISTENT_FILE error message is uninformative

### ISSUE THREAD

**Issue by tynanseltzer** [cs50/ide#25]
apache50 start with a non existent directory simply returns 
`Usage: apache50 [start VHOST_DIR|restart|reload|stop|status]` which confuses students. `Directory $VHOST_DIR does not exist` would be a much better choice.

**Comment by dmalan** [comment]
We've actually deprecated `apache50` in favor of `http-server`, as in CS50. No need to steer students toward it mid-semester, but the next version of CS50 IDE will only have the latter, fyi!

**Comment by tynanseltzer** [comment]
Thanks! I guess CS1 never got the memo.
