### ISSUE TITLE
How can I login as root inside cs50 IDE

### ISSUE THREAD

**Issue by notbotman** [cs50/ide#57]
![image](https://user-images.githubusercontent.com/74244707/103476937-dca86000-4ddf-11eb-83aa-4dc25b82dee9.png)

**Comment by dmalan** [comment]
The latest version of the IDE actually no longer has `sudo` enabled! What are you trying to install/configure?

**Comment by notbotman** [comment]
Ok, I tried to install php8.0, memcached and redis
