### ISSUE TITLE
New IDE version; problems with Git and profile

### ISSUE THREAD

**Issue by sgilbert-student** [cs50/ide#58]
Hello.
I noticed over the weekend that the IDE version changed.  Instead of the home folder ~/ there is now the home-workspace folder (~/workspace/). It seems as if in the new version the home folder (~/) is not persistent. The problem that this is creating for my classes is that most tools (right now I'm looking at git, with .gitconfig and .git-credentials) place their configuration files in the home directory. I believe most other tools do this as well (emacs & vi). In addition, in the past I've put course-specific environmental information in the .profile, also in the home directory.
If the home directory is no longer persistent, is there a workaround?
Thank you.
--Steve Gilbert

**Comment by TheRijn** [comment]
It seems more people had this problem. It has been fixed in a recent update to cs50/cli50.

**Comment by dmalan** [comment]
Sorry about that, this has been reverted back to the `~/` design!
