### ISSUE TITLE
noVNC fails to connect in online IDE

### ISSUE THREAD

**Issue by kzidane** [cs50/ide#59]
How do I use this at all?
I saw that the older "GUI tab" functionality has been retired in favour of a VNC based solution. However, whenever I go to CS50 -> GUI in the online version, I get a new tab of noVNC that fails to connect:

![2021-01-12-143156_1373x708_scrot](https://user-images.githubusercontent.com/628455/104327699-f4b86780-54e2-11eb-9d71-cf39624ca82f.png)

(I don't know why it's in German, not my locale)

_Originally posted by @pazz in https://github.com/cs50/ide/issues/43#issuecomment-758695404_

**Comment by kzidane** [comment]
@pazz this issue should be fixed now. Re locale, are you using a VPN by chance?

**Comment by pazz** [comment]
thanks! I can confirm it works (now i need some binary that uses X11 to test it :) 

locale: no, I'm not using a VPN. Perhaps it is my browser (chromium) which knows my gmail login and Google could know that I do not usually translate German websites..

Anyhow, cheers for the quick fix!
