### ISSUE TITLE
networking?

### ISSUE THREAD

**Issue by pazz** [cs50/ide#65]
This is probably more an issue with your AWS settings and not the IDE image itself but I'm never sure where to ask technical questions about CS50 tools..

I noticed that in the terminal of ide.cs50.io pretty much all outgoing network traffic except on port 80 is blocked (for good reasons I know). Question: are there any other exceptions?

I would love to set an exercise where students write some sort of chat client and the easiest way to do this would be to connect to some existing XMPP / IRC / Discord server. Any ideas how this could technically work from within the web IDE?
Cheers!

**Comment by kzidane** [comment]
What egress port are you trying to use?

**Comment by pazz** [comment]
So far I have tried to connect to a XMPP server on port 5222 as well as some private webserver at port 8123.
I don't know what egress is, sorry.

**Comment by kzidane** [comment]
No worries. Egress just means outgoing/outbound. Can these be proxied over 443 by chance (i.e., have a proxy server that listens on 443 and forwards traffic to these ports)?

**Comment by pazz** [comment]
Oh I see. That port is simply not blocked for outgoing traffic? Good to know. 
Yes, I could probably set something like that up (but then I could also use port 80 right?). I was hoping to directly connect to some official server on their port, e.g. 5222 for jabber. 

If you know if some other chat service that is still not blocked from the IDE image please let me know.
Otherwise please just close this issue. I understand that you want to limit network traffic.

**Comment by kzidane** [comment]
No, 443 and 80 should be open, so you should be able to use either or both. I also just opened outgoing 5222 for you. Let me know  if you need anything else!
