### ISSUE TITLE
noVNC not working, no GUI appearing

### ISSUE THREAD

**Issue by VishG28** [cs50/ide#66]
Hey, I keep trying to use the C9 GUI but when I click it nothing shows up. It does give me a confirmation that I'm connected but nothing shows up. This is what it looks like: https://gyazo.com/dfdc2f16794d7779dbd79a09e1b1985a

**Comment by kzidane** [comment]
Did you run your GUI-based program in a terminal tab and checked the GUI browser window again?

**Comment by VishG28** [comment]
No, I just clicked on the Cloud9 logo on the top left and clicked on GUI

**Comment by kzidane** [comment]
You need to run your GUI-based app in a terminal.

**Comment by VishG28** [comment]
how can i do that again?

**Comment by kzidane** [comment]
Do you have a GUI-based app that you're trying to run?

**Comment by VishG28** [comment]
Oh got it, now I know what you mean. Thanks
