### ISSUE TITLE
CS50 IDE can not reach 8080 port on exposed URL

### ISSUE THREAD

**Issue by swrjnthjr** [cs50/ide#67]
I am running a django server on port 8080 and IP set to 0.0.0.0

However when I click on the CS50 drop down and then web server the site seems to be unreachable.
Has anyone ever faced this issue, if so what are your resolution solutions?

More details:
```
~/Djangonew/lecture3/ $ python manage.py runserver 0.0.0.0:8080
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
February 12, 2021 - 08:57:32
Django version 3.1.5, using settings 'lecture3.settings'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
```

![image](https://user-images.githubusercontent.com/74957891/107748121-916a6100-6d3e-11eb-82c2-5b1a6c97173a.png)

**Comment by dmalan** [comment]
This should be fixed! https://cs50.statuspage.io/incidents/rj6kmr2bkrsd

**Comment by anugrahmasih261** [comment]
i can not use tha command python manage.py runserver when i get the link 127.0.0.1:8000 when i touch this link it says can not reach what to do if such probles occures to many students how we would use cs50 ide it becomes very hoppless in such condition when we dont find any solution anywhere even on google kindly include every solutions in your lectures
