### ISSUE TITLE
SVN's password

### ISSUE THREAD

**Issue by YueZHANa1787854** [cs50/ide#68]
Hi,

I forgot my svn password, is there any methods to retrieve and change my password?

<img width="254" alt="psw" src="https://user-images.githubusercontent.com/64507377/109476240-92cdb480-7ac6-11eb-96d9-e987b9c8169f.png">

Thanks for your help.

**Comment by dmalan** [comment]
Afraid CS50 IDE doesn't support `sudo` anymore!
