### ISSUE TITLE
How to fiz ide not showing `_`?

### ISSUE THREAD

**Issue by gabriellovate** [cs50/ide#76]
When I type `_` on the CS50 IDE it shows a space instead of a `_`on the screen. Is this behavior expected? Is there an obvious way of fixing it that I did not find?

**Comment by gabriellovate** [comment]
Sure @dmalan (:
So, this is my code on VS Code:
![image](https://user-images.githubusercontent.com/39889038/132873073-e2eeb4ce-d2c0-456e-a5c2-69fac360d67c.png)
And this is the same code on CS50 IDE:
![image](https://user-images.githubusercontent.com/39889038/132873154-235c0a34-bc12-43d1-9ae6-146dfb5a390c.png)

**Comment by gabriellovate** [comment]
A couple of extra informations: I am running the IDE on Brave browser Version 1.29.79 with Chromium 93.0.4577.63 (64-bit) on Fedora Workstation 34.

**Comment by dmalan** [comment]
Hm, do you see the same symptom on, e.g., Chrome or Firefox? Do you have any extensions in Brave that might be altering your font? Afraid this is the only report we've received, and I'm not able to reproduce in, e.g., Chrome:

<img width="334" alt="Screen Shot 2021-09-10 at 10 58 51 AM" src="https://user-images.githubusercontent.com/788678/132874348-47e84990-0654-4088-8100-78d6d929b971.png">

**Comment by gabriellovate** [comment]
I tested on Firefox and the IDE works flawlessly, sorry for all the fuz, I'll stick to a supported browser. Thanks for being supportive @dmalan (:
