### ISSUE TITLE
ide50 pulls latest image - again

### ISSUE THREAD

**Issue by memilanuk** [cs50/ide#78]
Running the offline CS50 IDE in Docker on an Ubuntu 20.04.3 LTS VM.

Is the expected behavior of 'sudo ide50 start' to pull the latest image again and again and again, or should it pull it *once*, and then only pull the image again when the command 'sudo ide50 update' is given?  Is there a way to make ide50 *not* pull the latest image every time it runs?

Currently, it will download and extract the latest image time after time after time, every 10 minutes if the start option is given.  This seems to be the exact opposite of the expected behavior of an 'offline' version of the IDE.

**Comment by dmalan** [comment]
That's actually the intended behavior, to decrease the probability that someone will end up with an especially out-of-date IDE (since we're often making changes). But you can do `ide50 -f start` to start it "fast" and skip updates!

**Comment by memilanuk** [comment]
Awesome, thanks for the response.

That said... maybe adding a blurb about the '-f' option to the help displayed via '-h' would be worth while?
